In [3021]:
from selenium import webdriver
import numpy as np

import time
from selenium import webdriver

from selenium.webdriver.common.by import By

from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support.expected_conditions import presence_of_element_located

from selenium.webdriver.support import expected_conditions
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
import time
from selenium import webdriver
from selenium.webdriver.chrome.service import Service
import pandas as pd

In [3022]:
from sklearn.preprocessing import LabelEncoder


label_encoder = LabelEncoder()

In [3023]:

pd.set_option('display.max_columns', None)

In [3024]:

pd.set_option('display.max_rows', None)

In [3025]:
df1 = pd.read_csv(r'A:\Учёба\практика 2 курс\data\citilink/laptop/data.csv')
df2 = pd.read_csv(r'A:\Учёба\практика 2 курс\data\eldorado/laptop/data.csv')

In [3026]:
df1.replace("есть", 1, inplace=True)
df2.replace("есть", 1, inplace=True)

df1.replace("да", 1, inplace=True)
df2.replace("да", 1, inplace=True)

df1.replace("нет", 1, inplace=True)
df2.replace("нет", 1, inplace=True)

df1.replace("Нет", 1, inplace=True)
df2.replace("Нет", 1, inplace=True)

df1.replace("Есть ", 1, inplace=True)
df2.replace("Есть ", 1, inplace=True)

df1.replace("Есть", 1, inplace=True)
df2.replace("Есть", 1, inplace=True)

In [3027]:
df1 = df1.fillna(0)
df2 = df2.fillna(0)

In [3028]:
columns1 = df1.columns
columns2 = df2.columns

In [3029]:
set(columns1) & set(columns2)

{'Вес',
 'Время отклика',
 'Гарантия',
 'Емкость',
 'Количество отзывов',
 'Количество ядер',
 'Количество ячеек',
 'Название',
 'Операционная система',
 'Поверхность',
 'Подсветка клавиш',
 'Рейтинг',
 'Сенсорный',
 'Соотношение сторон',
 'Тип',
 'Тип вилки',
 'Тип матрицы',
 'Цена',
 'Язык клавиатуры',
 'Яркость'}

In [3030]:
df1[df1.ne(0)].count().sort_values(ascending=False)


link                                                  528
Название                                              528
Цена                                                  528
Рейтинг                                               515
Цветовое                                              462
Гарантия                                              452
Вес                                                   451
Веб-камера                                            447
Операционная система                                  445
Поддержка технологии                                  443
Язык клавиатуры                                       443
Тип                                                   442
Процессор,                                            442
Количество ядер                                       442
Количество высокопроизводительных ядер                441
Техпроцесс                                            441
Процессор                                             441
Объем кэша L2 

In [3031]:
df1['Количество высокопроизводительных ядер']

0      0.0
1      0.0
2      0.0
3      6.0
4      4.0
5      4.0
6      8.0
7      4.0
8      8.0
9      6.0
10     4.0
11     6.0
12     6.0
13     2.0
14     6.0
15     6.0
16     6.0
17     6.0
18     4.0
19     2.0
20     4.0
21     4.0
22     8.0
23     8.0
24     6.0
25     2.0
26     2.0
27     6.0
28     4.0
29     0.0
30     4.0
31     4.0
32     2.0
33     6.0
34     6.0
35     4.0
36     0.0
37     0.0
38     0.0
39     0.0
40     6.0
41     0.0
42     0.0
43     0.0
44     6.0
45     0.0
46     0.0
47     0.0
48     4.0
49     0.0
50     0.0
51     4.0
52     6.0
53     0.0
54     0.0
55     0.0
56     2.0
57     0.0
58     0.0
59     2.0
60     0.0
61     0.0
62     0.0
63     0.0
64     0.0
65     0.0
66     0.0
67     0.0
68     0.0
69     0.0
70     4.0
71     0.0
72     6.0
73     0.0
74     0.0
75     6.0
76     0.0
77     6.0
78     6.0
79     0.0
80     6.0
81     6.0
82     0.0
83     0.0
84     0.0
85     0.0
86     0.0
87     0.0
88     4.0
89     6.0
90     0.0

In [3032]:
df1['Процессор']

0                                       0
1                                       0
2                                       0
3                       AMD Ryzen 5 5600U
4                    Intel Core i5 10210U
5                    Intel Core i7 1065G7
6                       AMD Ryzen 7 5700U
7                    Intel Core i5 1135G7
8                    Intel Core i7 11800H
9                    Intel Core i5 11400H
10                   Intel Core i5 1135G7
11                   Intel Core i7 12700H
12                      AMD Ryzen 5 5625U
13                   Intel Core i3 1115G4
14                   Intel Core i5 11400H
15                      AMD Ryzen 5 5625U
16                   Intel Core i5 11400H
17                   Intel Core i5 11400H
18                   Intel Core i5 12500H
19                   Intel Core i3 10110U
20                   Intel Core i5 12450H
21                   Intel Core i5 1155G7
22                   Intel Core i7 11800H
23                   Intel Core i7

In [3033]:
df2['Модель процессора']

0             Ryzen 7 4800H
1            Core i3-1115G4
2             Ryzen 5 4600H
3             Ryzen 5 3500U
4            Core i5-11400H
5                  Apple M1
6            Core i5-1135G7
7            Core i5-1155G7
8            Core i5-1135G7
9            Core i5-12500H
10            Ryzen 5 4600H
11            Celeron N4020
12           Core i5-11400H
13           Core i5-1135G7
14           Core i5-11320H
15            Ryzen 5 5600H
16           Core i7-12700H
17           Core i5-12450H
18           Core i5-12450H
19           Core i5-11400H
20           Core i3-1115G4
21           Core i3-1115G4
22           Core i3-1115G4
23            Ryzen 5 5600H
24            Celeron N4120
25           Core i5-1135G7
26           Core i5-12450H
27                 Apple M1
28           Core i5-11260H
29                 Apple M1
30           Core i5-12450H
31           Core i7-12700H
32           Core i3-1115G4
33           Core i9-12900H
34           Core i7-12700H
35           Core i7

In [3034]:
set(columns1)

{'Delta E',
 'Delta E Цвета',
 'Kensington',
 'RTX Studio',
 'TGP',
 'Touch',
 'link',
 'Акустическая',
 'Антибактериальное покрытие',
 'Веб-камера',
 'Версия HDMI',
 'Вес',
 'Вес упаковки (ед)',
 'Внешняя',
 'Внутренняя',
 'Возможность апгрейда HDD/SSD',
 'Возможность апгрейда оперативной памяти',
 'Возможность зарядки от Type-C (USB Power Delivery)',
 'Возможность передачи видео через USB Type-C',
 'Время отклика',
 'Встроенный сабвуфер',
 'Выходная мощность адаптера питания',
 'Габариты упаковки (ед) ДхШхВ',
 'Гарантийный ремонт(причина ремонта)',
 'Гарантия',
 'Графический',
 'Диагональ экрана в',
 'Динамический экран',
 'Для геймеров',
 'Для дизайна',
 'Для работы',
 'Для учебы',
 'Емкость',
 'Кабельная',
 'Кард-ридер',
 'Количество высокопроизводительных ядер',
 'Количество занятых слотов оперативной',
 'Количество микрофонов',
 'Количество отзывов',
 'Количество разъемов жесткого диска',
 'Количество свободных разъемов жесткого диска',
 'Количество свободных слотов оперативной',

In [3035]:
set(columns2)

{'4G (LTE)',
 'Bluetooth',
 'DVI',
 'DisplayPort',
 'Ethernet',
 'HDMI',
 'LED-подсветка',
 'Micro HDMI',
 'Micro USB 2.0',
 'Mini DisplayPort',
 'Mini HDMI',
 'RJ-45',
 'Thunderbolt 3',
 'Thunderbolt/USB 4',
 'USB',
 'USB 2.0',
 'USB 2.0 (Type-C)',
 'USB 3.0',
 'USB 3.0 (Type-C)',
 'USB 3.1',
 'USB 3.1 (Type-C)',
 'USB 3.2',
 'USB 3.2 (Type-C)',
 'Unnamed: 112',
 'VGA (D-Sub)',
 'Web-камера',
 'Wi-Fi',
 'Блок питания',
 'Версия Bluetooth',
 'Вес',
 'Время отклика',
 'Встроенные динамики',
 'Высота',
 'Гарантия',
 'Глубина',
 'Датчик освещенности',
 'Диагональ экрана',
 'Дополнительная информация',
 'Емкость',
 'Игровой ноутбук',
 'Интерфейс подключения',
 'Кабель для зарядки',
 'Картридер',
 'Количество динамиков',
 'Количество отзывов',
 'Количество потоков',
 'Количество слотов',
 'Количество ядер',
 'Количество ядер графического процессора',
 'Количество ячеек',
 'Контрастность',
 'Кэш L2',
 'Кэш L3',
 'Максимальная тактовая частота',
 'Максимальная частота обновления',
 'Максималь

In [3036]:

name_old = 'Модель процессора'
name_new = 'Процессор'
df2.rename(columns={name_old: name_new}, inplace=True)

In [3037]:
name_old = 'Максимальная частота обновления'
name_new = 'Частота обновления'
df2.rename(columns={name_old: name_new}, inplace=True)

In [3038]:


name_old = 'Максимальная частота обновления'
name_new = 'Частота обновления'
df2.rename(columns={name_old: name_new}, inplace=True)

In [3039]:
 
name_old = 'Максимальный объем'
name_new = 'Объем'
df2.rename(columns={name_old: name_new}, inplace=True)

In [3040]:

name_old = 'Настройка подсветки клавиатуры'
name_new = 'Цвет подсветки клавиатуры'
df2.rename(columns={name_old: name_new}, inplace=True)

In [3041]:

name_old = 'Модель видеокарты'
name_new = 'Графический'
df2.rename(columns={name_old: name_new}, inplace=True)

In [3042]:

name_old = 'Количество потоков'
name_new = 'Максимальное число потоков'
df2.rename(columns={name_old: name_new}, inplace=True)

In [3043]:

name_old = 'Количество слотов'
name_new = 'Количество слотов оперативной'
df2.rename(columns={name_old: name_new}, inplace=True)

In [3044]:

name_old = 'Картридер'
name_new = 'Кард-ридер'
df2.rename(columns={name_old: name_new}, inplace=True)

In [3045]:
name_old = 'Web-камера'
name_new = 'Веб-камера'
df2.rename(columns={name_old: name_new}, inplace=True)

In [3046]:
name_old = 'USB 2.0 (Type-C)'
name_new = 'Порты USB 2.1 (Type-C)'
df2.rename(columns={name_old: name_new}, inplace=True)

In [3047]:
name_old = 'Оперативная'
name_new = 'Объем оперативной памяти'
df1.rename(columns={name_old: name_new}, inplace=True)

In [3048]:
name_old = 'USB 3.0 (Type-C)'
name_new = 'Порты USB 3.0 (Type-C)'
df2.rename(columns={name_old: name_new}, inplace=True)

In [3049]:
name_old = 'USB 3.1 (Type-C)'
name_new = 'Порты USB 3.1 (Type-C)'
df2.rename(columns={name_old: name_new}, inplace=True)

In [3050]:
name_old = 'USB 3.2 (Type-C)'
name_new = 'Порты USB 3.2 (Type-C)'
df2.rename(columns={name_old: name_new}, inplace=True)

In [3051]:

name_old = 'Мощность блока питания'
name_new = 'Выходная мощность адаптера питания'
df2.rename(columns={name_old: name_new}, inplace=True)

In [3052]:

name_old = 'Количество ядер графического процессора'
name_new = 'Количество высокопроизводительных ядер'
df2.rename(columns={name_old: name_new}, inplace=True)

In [3053]:


name_old = 'Диагональ экрана в'
name_new = 'Диагональ экрана'
df1.rename(columns={name_old: name_new}, inplace=True)

In [3054]:

name_old = 'Технология динамического экрана'
name_new = 'Динамический экран'
df2.rename(columns={name_old: name_new}, inplace=True)

In [3055]:

name_old = 'Игровой ноутбук'
name_new = 'Для геймеров'
df2.rename(columns={name_old: name_new}, inplace=True)

In [3056]:
df1 = df1.fillna(0)
df2 = df2.fillna(0)

In [3057]:
column = set(df1.columns) & set(df2.columns)

df_full = df1.loc[:, column]

df_full.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 528 entries, 0 to 527
Data columns (total 36 columns):
 #   Column                                  Non-Null Count  Dtype  
---  ------                                  --------------  -----  
 0   Название                                528 non-null    object 
 1   Время отклика                           528 non-null    object 
 2   Порты USB 3.1 (Type-C)                  528 non-null    float64
 3   Графический                             528 non-null    object 
 4   Объем                                   528 non-null    object 
 5   Тип матрицы                             528 non-null    object 
 6   Веб-камера                              528 non-null    object 
 7   Диагональ экрана                        528 non-null    object 
 8   Гарантия                                528 non-null    object 
 9   Рейтинг                                 528 non-null    object 
 10  Порты USB 3.0 (Type-C)                  528 non-null    float6

C:\Users\ilya\AppData\Local\Temp\ipykernel_6660\3155891446.py:3: FutureWarning: Passing a set as an indexer is deprecated and will raise in a future version. Use a list instead.
  df_full = df1.loc[:, column]


In [3058]:
column = 'Для геймеров'

In [3059]:
print(df1[column][df1[column] != 0 ].unique())
print(df2[column][df2[column] != 0 ].unique())

[1.]
[1.]


In [3060]:
column = 'Цена'

In [3061]:
def func(s):
    try:
        if "Нет в наличии" in s:
            return 0.0
        elif "₽" in s:
            return float(s.replace("₽", "").replace(" ", "").replace(",", "."))
        elif "р." in s:
            return int(s.replace("р.", "").replace(" ", ""))
        else:
            return int(s.replace(" ", ""))
 
    except Exception:
        pass



df1[column] = df1[column].apply(func)
df2[column] = df2[column].apply(func)

In [3062]:
column = 'Количество слотов оперативной'

In [3063]:
print(df1[column][df1[column] != 0 ].unique())
print(df2[column][df2[column] != 0 ].unique())

[2. 1.]
[2. 1. 4.]


In [3064]:
column = 'Вес'


In [3065]:
def func(s):
    try :
        if s == 0:
            return 0.0
        elif " кг" in s:
            return float(s.split(" ")[0])

    except Exception:
        pass

df1[column] = df1[column].apply(func)
df2[column] = df2[column].apply(func)

In [3066]:
print(df1[column][df1[column] != 0 ].unique())
print(df2[column][df2[column] != 0 ].unique())

[1.7   1.87  1.8   1.56  2.38  1.86  2.25  1.4   1.53  2.6   1.5   1.71
 1.38  1.94  1.79  1.78  1.54  2.5   1.75  2.9   2.14  2.66  2.8   2.1
 1.65  2.35  1.63  2.    1.74  1.9   1.6   3.3   1.85  1.46  2.15  2.3
 1.95  1.77  1.55  0.97  2.7   2.17  1.3   1.61  1.88  2.2   1.69  0.98
 1.273 1.99  1.92  2.49  1.82  1.47  2.39  1.51  2.02  1.26  2.75  1.52
 1.14  1.24  1.49  2.26  2.46  1.66  1.16  2.315 1.57  1.29  1.25  1.39
 2.4   1.59  1.724 1.728 1.12  2.231 1.2   1.32  1.35  1.36  1.845 1.27 ]
[1.7   1.65  1.8   2.15  1.29  1.56  2.25  2.3   1.5   1.71  2.5   2.2
 1.38  1.73  1.76  1.43  1.63  1.99  2.58  1.273 1.6   0.935 1.25  1.27
 1.54  2.1   1.9   2.4   1.1   2.6   1.88  1.57  1.26  1.75  1.2   2.18
 1.85  1.94  1.28  1.47  1.49  1.68  2.9   1.4   1.69  1.55  1.53  2.
 1.34  1.41  1.59  1.46  1.24  1.48  1.78  1.86  2.52  1.44  1.61  2.82
 3.    1.36  0.918 1.42  1.74  2.49  3.3   3.1   1.3   1.17  1.64  1.45
 1.87  2.36  2.02  1.33  2.7   2.19  1.31  1.51  2.17  1.12 ]


In [3067]:
column = 'Операционная система'

df1[column] = df1[column].str.lower()
df2[column] = df2[column].str.lower()

In [3068]:
def func(s):
    try:
        if s == 0:
            return 0.0
        if "macos" in s:
            return "mac"
        elif " " in s:
            return s.split(" ")[0]
        else:
            return s
    except Exception:
        pass
df1[column] = df1[column].apply(func)
df2[column] = df2[column].apply(func)

In [3069]:
combined_column = pd.concat([df1[column], df2[column]])


label_encoder.fit(combined_column.astype(str))


df1[column] = label_encoder.transform(df1[column].astype(str))
df2[column] = label_encoder.transform(df2[column].astype(str))

In [3070]:
print(df1[column][df1[column] != 0 ].unique())
print(df2[column][df2[column] != 0 ].unique())

[ 9 10  4  3  7  1  6  8]
[10  5  7  9  2  6]


In [3071]:
column = 'Частота обновления'

In [3072]:
def func(s):
    try:
        if s == 0:
            return 0.0
        if " Гц" in s:
            return float(s.split(" Гц")[0])
        else:
            return s
    except Exception:
        pass
df1[column] = df1[column].apply(func)
df2[column] = df2[column].apply(func)

In [3073]:
print(df1[column][df1[column] != 0 ].unique())
print(df2[column][df2[column] != 0 ].unique())

[ 60. 144. 165. 240. 120.  90.]
[ 60. 144. 165.  90. 120.  50. 240. 360.]


In [3074]:
column = 'Объем оперативной памяти'

In [3075]:
def func(s):
    try:
        if s == 0:
            return 0.0
        if " ГБ" in s:
            return float(s.split(" ГБ")[0])
        else:
            return s
    except Exception:
        pass
df1[column] = df1[column].apply(func)
df2[column] = df2[column].apply(func)

In [3076]:
print(df1[column][df1[column] != 0 ].unique())
print(df2[column][df2[column] != 0 ].unique())

[ 8. 16. 32.  4. 64. 12.  2.]
[16.  8.  4. 32.  2. 12. 64. 24.]


In [3077]:
column = 'Количество ячеек'

In [3078]:
def func(s):
    try:
        if s == 0:
            return 0.0
        if " cell" in s:
            return float(s.split(" cell")[0])
        else:
            return s
    except Exception:
        pass



df1[column] = df1[column].apply(func)


In [3079]:
print(df1[column][df1[column] != 0 ].unique())
print(df2[column][df2[column] != 0 ].unique())

[2. 4. 3. 6.]
[2. 3. 4.]


In [3080]:
column = 'Яркость'

In [3081]:
def func(s):
    try:
        if s == 0:
            return 0.0
        if "кд" in s:
            return float(s.split("кд")[0])
        else:
            return s
    except Exception:
        pass


df1[column] = df1[column].apply(func)
df2[column] = df2[column].apply(func)

In [3082]:
print(df1[column][df1[column] != 0 ].unique())
print(df2[column][df2[column] != 0 ].unique())

[ 250.  200.  300.  400.  220.  600. 1000.  550. 1600.  500.  350.  205.]
[ 400.  250.  300.  220.  350. 1000. 1600.  500.]


In [3083]:
column = 'Тип вилки'

In [3084]:
def func(s):
    try:
        if "Тип" in s:
          return (s.replace(s.split('Тип')[0],""))[0:5]
        
        return s
        
    except Exception:
        pass



df1[column] = df1[column].apply(func)
df2[column] = df2[column].apply(func)

In [3085]:

combined_column = pd.concat([df1[column], df2[column]])


label_encoder.fit(combined_column.astype(str))


df1[column] = label_encoder.transform(df1[column].astype(str))
df2[column] = label_encoder.transform(df2[column].astype(str))

In [3086]:
print(df1[column][df1[column] != 0 ].unique())
print(df2[column][df2[column] != 0 ].unique())

[5 1 2 3]
[1 2 5 4 3 6]


In [3087]:
column = 'Соотношение сторон'



In [3088]:

combined_column = pd.concat([df1[column], df2[column]])


label_encoder.fit(combined_column.astype(str))


df1[column] = label_encoder.transform(df1[column].astype(str))
df2[column] = label_encoder.transform(df2[column].astype(str))

In [3089]:
print(df1[column][df1[column] != 0 ].unique())
print(df2[column][df2[column] != 0 ].unique())

[2 4 1 3]
[2 1 4]


In [3090]:
column = 'Максимальное число потоков'

In [3091]:
def func(s):
    try:
        if "шт" in s:
          return float(s.split(" шт")[0])
        
        return s
        
    except Exception:
        pass



df1[column] = df1[column].apply(func)

In [3092]:
print(df1[column][df1[column] != 0 ].unique())
print(df2[column][df2[column] != 0 ].unique())

[nan 12.  8. 16. 20.  4.  2. 24. 10.]
[ 4. 12.  8. 16. 20.  2. 24.  6. 32.]


In [3093]:
column = 'Емкость'

In [3094]:
def func(s):
    try:
        if " " in s:
          return float(s.split(" ")[0])
        
        return s
        
    except Exception:
        pass



df1[column] = df1[column].apply(func)
df2[column] = df2[column].apply(func)

In [3095]:
print(df1[column][df1[column] != 0 ].unique())
print(df2[column][df2[column] != 0 ].unique())

[  nan 4800. 4250. 5700. 3665. 4000. 6060. 5000. 6875. 3410. 7200. 4200.
 5040. 6000. 5400. 4500. 4825. 3800. 8000. 3610. 4700. 3950. 5500. 3500.
 4100. 7330. 3465. 4900. 3378.]
[  42.   3400.       nan   37.   4562.   5000.     46.   5600.     53.5
 4800.   4550.   4129.   3410.   4500.   2500.   8000.     45.     50.
   56.   3800.   4000.     41.     38.   3220.     71.   3275.     76.
   70.   3600.   4200.   6060.   5280.   6250.     84.     49.9  6500.
  100.     54.     82.     51.     90.     58.2    46.2    53.35 5700.
 3175.     60.     63.   3000.     52.6  7000.     36.   5400.     80.
   69.99 4350.     19.9  4330.   5200.     65.     75.     35.   4530.
   66.5    59.     43.     57.  ]


In [3096]:
column = 'Выходная мощность адаптера питания'

In [3097]:
def func(s):
    try:
        if " Вт" in s:
          return float(s.replace(" Вт", ""))
        
        return s
        
    except Exception:
        pass



df1[column] = df1[column].apply(func)
df2[column] = df2[column].apply(func)

In [3098]:
print(df1[column][df1[column] != 0 ].unique())
print(df2[column][df2[column] != 0 ].unique())

[   nan  65.   280.   150.   240.    90.   170.   120.   180.    45.
 230.   330.    64.98 200.   100.    35.    30.   135.   300.    57.  ]
[ nan  30. 150.  45.  65. 170.  67. 140.  96. 100. 120. 280. 180.  95.
 300. 135.]


In [3099]:
def func(s):
    try:
        if " " in s:
          return s.replace(" ", "")
        
        return s
        
    except Exception:
        pass



df1[column] = df1[column].apply(func)
df2[column] = df2[column].apply(func)

In [3100]:

combined_column = pd.concat([df1[column], df2[column]])


label_encoder.fit(combined_column.astype(str))


df1[column] = label_encoder.transform(df1[column].astype(str))
df2[column] = label_encoder.transform(df2[column].astype(str))

In [3101]:
print(df1[column][df1[column] != 0 ].unique())
print(df2[column][df2[column] != 0 ].unique())

[]
[]


In [3102]:
column = 'Количество ядер'

In [3103]:
def func(s):
    try:
        if s == 0:
            return 0.0
        
        if "-ядерный" in s:
            return float(s.split("-ядерный")[0])
        else:
            return float(s)

    except Exception:
        pass



df1[column] = df1[column].apply(func)

In [3104]:
print(df1[column][df1[column] != 0 ].unique())
print(df2[column][df2[column] != 0 ].unique())

[ 6.  4.  8. 14.  2. 12. 10. 16.]
[ 8.  2.  6.  4. 12. 14. 10. 16. 24.]


In [3105]:
column = 'Рейтинг'

In [3106]:
def func(s):
    try:
        if s == 0:
            return 0.0
        
        if "Код товара" in s:
            return 0.0
        elif "Обзор" in s:
            return float(s.split(" Обзор")[0])
        else:
            return float(s)

    except Exception:
        pass



df1[column] = df1[column].apply(func)

In [3107]:
print(df2[column][df2[column] != 0 ].unique())
print(df1[column][df1[column] != 0 ].unique())

[5. 4.]
[4.9 5.  4.8 4.6 4.7 4.2 4.3 4.4 4.  3.  4.1 1.  2.  4.5 3.5]


In [3108]:
column = 'Гарантия'

In [3109]:
def func(s):
    try :
        if s == 0:
            return 0.0
        elif "год" in s:
            return int(s.split(" ")[0])* 12
        elif "мес." in s:
            return int(s.split(" ")[0])


    except Exception:
        pass

df1[column] = df1[column].apply(func)
df2[column] = df2[column].apply(func)

In [3110]:
print(df2[column][df2[column] != 0 ].unique())
print(df1[column][df1[column] != 0 ].unique())

[12 24]
[12. 24. 13.]


In [3111]:
column = 'Количество высокопроизводительных ядер'

In [3112]:
print(df2[column][df2[column] != 0 ].unique())
print(df1[column][df1[column] != 0 ].unique())

[ 8. 16. 19.  7. 14. 10.]
[6. 4. 8. 2.]


In [3113]:
column = 'Диагональ экрана'

In [3114]:
def func(s):
    try :
        if s == 0:
            return 0.0
        elif '"' in s:
            return float(s.split('"')[0].replace(" ",''))


    except Exception:
        pass

df1[column] = df1[column].apply(func)
df2[column] = df2[column].apply(func)

In [3115]:

combined_column = pd.concat([df1[column], df2[column]])


label_encoder.fit(combined_column.astype(str))


df1[column] = label_encoder.transform(df1[column].astype(str))
df2[column] = label_encoder.transform(df2[column].astype(str))

In [3116]:
df2[column][df2[column] != 0 ].unique()

array([13,  4, 15, 14, 18,  6,  8,  1, 12,  7, 16, 19,  2, 17,  5, 10,  3,
       11])

In [3117]:
df1[column][df1[column] != 0 ].unique()

array([13,  6, 18, 14,  7, 15, 16,  8,  2,  4, 17, 11,  5,  9])

In [3118]:
column = 'Веб-камера'

In [3119]:
def func(s):
    try:
        if s == 'встроенная':
            return 1
        elif s != 0:
          return 1
        
        return s
        
    except Exception:
        pass

df1[column] = df1[column].apply(func)
df2[column] = df2[column].apply(func)

In [3120]:
df1[column][df1[column] != 0 ].unique()

array([1], dtype=int64)

In [3121]:
df2[column][df2[column] != 0 ].unique()

array([1], dtype=int64)

In [3122]:
column = 'Тип матрицы'

In [3123]:
def func(s):
    try:
        if " " in s:
          return (s.split(" ")[0] + s.split(" ")[1])
        
        return s
        
    except Exception:
        pass



df1[column] = df1[column].apply(func)
df2[column] = df2[column].apply(func)

In [3124]:

combined_column = pd.concat([df1[column], df2[column]])


label_encoder.fit(combined_column.astype(str))


df1[column] = label_encoder.transform(df1[column].astype(str))
df2[column] = label_encoder.transform(df2[column].astype(str))

In [3125]:
df1[column][df1[column] != 0 ].unique()

array([5, 2, 8, 6, 9, 7])

In [3126]:
df2[column][df2[column] != 0 ].unique()

array([ 5,  2,  3,  8,  4, 10,  6,  1])

In [3127]:
column = 'Графический'

df1[column] = df1[column].str.lower()
df2[column] = df2[column].str.lower()

In [3128]:
def func(s):
    try:
        if "nvidia" in s:
            return s.split(" - ")[0].replace("nvidia ", "")
        else:
            return s
    except Exception:
        pass

df1[column] = df1[column].apply(func)

In [3129]:
from sklearn.preprocessing import LabelEncoder


label_encoder = LabelEncoder()


combined_column = pd.concat([df1[column], df2[column]])


label_encoder.fit(combined_column.astype(str))


df1[column] = label_encoder.transform(df1[column].astype(str))
df2[column] = label_encoder.transform(df2[column].astype(str))

In [3130]:
df1[column][df1[column] != 0 ].unique()

array([ 3, 64, 19, 62, 36, 29, 32, 17, 27,  9, 10, 59,  8, 66, 55, 21, 35,
        7, 65, 39, 16,  2,  6, 18, 22, 56, 20,  5, 49,  4, 69, 63, 42, 24,
       44, 31, 25, 46, 68, 61, 67, 60, 23, 88, 75])

In [3131]:
df2[column][df2[column] != 0 ].unique()

array([77, 90, 76, 74, 25, 12, 62, 72, 31, 16, 91, 70, 64, 32, 29, 35, 92,
       27, 58, 53, 86, 54, 56, 57, 79, 20, 82, 66, 65, 21, 83, 26, 94, 80,
       81, 30, 36, 15, 93, 85, 11, 40, 43, 28, 87, 13, 41, 37, 46, 14,  1,
       48, 45, 71, 47, 84, 51,  3, 50, 38, 18, 95, 73, 33, 89, 22, 78, 34,
       52])

In [3132]:
column = 'Время отклика'

In [3133]:
def func(s):
    try:
        if "мс" in s:
            return float(s.replace(" мс", ""))
        else:
            return s
    except Exception:
        pass



df1[column] = df1[column].apply(func)
df2[column] = df2[column].apply(func)

In [3134]:
df2[column][df2[column] != 0 ].unique()

array([nan,  3.])

In [3135]:
df1[column][df1[column] != 0 ].unique()

array([ nan, 11. ,  0.2,  5. ,  1. ,  3. , 16. , 27. ,  7. , 35. ])

In [3136]:
column = 'Процессор'

df1[column] = df1[column].str.lower()
df2[column] = df2[column].str.lower()

In [3137]:
def func(s):
    try:
        if "amd " in s:
            return s.replace("amd ", "")
        elif "intel " in s:
            return s.replace("intel ", "")
        else:
            return s
    except Exception:
        pass

df1[column] = df1[column].apply(func)

In [3138]:

combined_column = pd.concat([df1[column], df2[column]])


label_encoder.fit(combined_column.astype(str))


df1[column] = label_encoder.transform(df1[column].astype(str))
df2[column] = label_encoder.transform(df2[column].astype(str))

In [3139]:
print(df1[column][df1[column] != 0 ].unique())
print(df2[column][df2[column] != 0 ].unique())

[127  33  67 136  38  73  39  77 128  25  46  24  45  41 110 122  34 116
  68 124 113 125  42  70  98  75 126 121  19  11 114 139  44  99  23  16
 137 117  36  26  35  72  69   5 141   3 115   6 138  43 109  74  71 129
  79 143  22 119  13   8  18  49 130 131  86  78 144  28 142  47 118  83
 100  81  85  84 132  48  82  80 140  10 120   2 133  27  37  21  40  50
  76]
[135  31 124 122  58   1  57  59  63  18  56 126  93  62  20  54 101  51
  91 112  17 125  30  11  12 111 117  55 113  66  29  61  87 116  90 137
  92   9  88  60  52  19 102 103 123 107  96  95  14   4  15  53  64 106
 118   7  32  22 104  97  65 105 108 129 140 127  89  94 131 128 134 114]


In [3140]:
print(len(df1[column][df1[column] != 0 ].unique()))
print(len(df2[column][df2[column] != 0 ].unique()))

91
72


In [3141]:
column = 'Название'

df1[column] = df1[column].str.lower()
df2[column] = df2[column].str.lower()

In [3142]:
def func(s):
    try:
        if "," in s:
            return s.split(",")[0]
        else:
            return s
    except Exception:
        pass



df1[column] = df1[column].apply(func)
df2[column] = df2[column].apply(func)

In [3143]:
df1[column][df1[column] != 0 ].head(10)

0                ноутбук huawei matebook d 16 16"
1           ноутбук huawei matebook d 15 bod-wdh9
2           ноутбук huawei matebook d 15 bod-wdi9
3                ноутбук hiper expertbook mtl1577
4                      ноутбук digma pro fortis m
5                       ноутбук asus a516jp-ej461
6           ноутбук huawei matebook d 15 bom-wfp9
7                      ноутбук hiper dzen mtl1569
8    ноутбук игровой msi gp66 leopard 11ug-699xru
9                                               ‌
Name: Название, dtype: object

In [3144]:
df2[column][df2[column] != 0 ].head(10)

0                           ноутбук asus m1502ia-bq093
1                  ноутбук haier i1510sd (jb0b1be00ru)
2    ноутбук asus vivobook 15 m1502i (90nb0y52-m002r0)
3                           ноутбук asus m515da-ej1697
4    игровой ноутбук thunderobot 911 air wave d (jt...
5    ноутбук apple macbook air 13 m1/8/256gb space ...
6    ноутбук huawei matebook d15 bod-wdh9 i5/8gb/51...
7    ноутбук huawei matebook d15 i5-1155g7/16/512 s...
8    ноутбук honor magicbook x 15 i5 8+512gb space ...
9          игровой ноутбук msi katana gf66 12ue-1084ru
Name: Название, dtype: object

In [3145]:
df1['Количество отзывов'] = pd.DataFrame({'Количество отзывов': np.random.normal(loc=10, scale=5, size=100)}).round(0)
df2['Количество отзывов'] = pd.DataFrame({'Количество отзывов': np.random.normal(loc=10, scale=5, size=100)}).round(0)

df1['Количество отзывов'] = df1['Количество отзывов'].clip(1, 30)
df1['Количество отзывов'] = df1['Количество отзывов'].clip(1, 30)

In [3146]:
column = set(df1.columns) & set(df2.columns)

df_full = df1.loc[:, column]

df_full.drop(columns = ['Объем', 'Поверхность', 'Кард-ридер', 'Язык клавиатуры','Тип'], inplace = True)

df_full.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 528 entries, 0 to 527
Data columns (total 31 columns):
 #   Column                                  Non-Null Count  Dtype  
---  ------                                  --------------  -----  
 0   Название                                528 non-null    object 
 1   Время отклика                           25 non-null     float64
 2   Порты USB 3.1 (Type-C)                  528 non-null    float64
 3   Графический                             528 non-null    int32  
 4   Тип матрицы                             528 non-null    int32  
 5   Веб-камера                              528 non-null    int64  
 6   Диагональ экрана                        528 non-null    int32  
 7   Гарантия                                528 non-null    float64
 8   Рейтинг                                 528 non-null    float64
 9   Порты USB 3.0 (Type-C)                  528 non-null    float64
 10  Количество ядер                         528 non-null    float6

C:\Users\ilya\AppData\Local\Temp\ipykernel_6660\1083508646.py:3: FutureWarning: Passing a set as an indexer is deprecated and will raise in a future version. Use a list instead.
  df_full = df1.loc[:, column]


In [3147]:
df1 = df1.fillna(0)
df2 = df2.fillna(0)

In [3148]:
column = df_full.columns

df1 = df1.loc[:, column]
df2 = df2.loc[:, column]

df1.to_csv(f'data_citilink.csv', index=False)
df2.to_csv(f'data_eldorado.csv', index=False)