In [156]:
from selenium import webdriver
import numpy as np

import time
from selenium import webdriver

from selenium.webdriver.common.by import By

from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support.expected_conditions import presence_of_element_located

from selenium.webdriver.support import expected_conditions
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
import time
from selenium import webdriver
from selenium.webdriver.chrome.service import Service
import pandas as pd

In [157]:

pd.set_option('display.max_columns', None)

In [158]:
df1 = pd.read_csv(r'A:\Учёба\практика 2 курс\data\citilink/tv/data.csv')
df2 = pd.read_csv(r'A:\Учёба\практика 2 курс\data\eldorado/tv/data.csv')

In [159]:
df1.replace("есть", 1, inplace=True)
df2.replace("есть", 1, inplace=True)

df1.replace("Есть ", 1, inplace=True)
df2.replace("Есть ", 1, inplace=True)

df1.replace("Есть", 1, inplace=True)
df2.replace("Есть", 1, inplace=True)

In [160]:
df1 = df1.fillna(0)
df2 = df2.fillna(0)

In [161]:
columns1 = df1.columns
columns2 = df2.columns

In [162]:
text_features = ['Встроенный сабвуфер', 'Название', 'Операционная система', 'Поддержка HDR', 'Прогрессивная развертка', 'Родительский контроль','Телетекст','Цифровое шумоподавление']  
numeric_features = ['Мощность сабвуфера', 'Вес без подставки','Гарантия','Диагональ','Количество отзывов','Контрастность','Рейтинг','Цвет','Цена','Частота обновления']  


In [163]:
df1['Название'] = df1['Название'].str.lower()
df2['Название'] = df2['Название'].str.lower()

In [164]:
set(columns1) & set(columns2)

{'Акустическая схема',
 'Вес без подставки',
 'Встроенный сабвуфер',
 'Гарантия',
 'Диагональ',
 'Количество отзывов',
 'Контрастность',
 'Мощность сабвуфера',
 'Название',
 'Объем встроенной памяти',
 'Объем оперативной памяти',
 'Операционная система',
 'Поддержка HDR',
 'Прогрессивная развертка',
 'Рейтинг',
 'Родительский контроль',
 'Телетекст',
 'Цвет',
 'Цена',
 'Цифровое шумоподавление',
 'Частота обновления'}

In [165]:
column = 'Частота обновления'

In [166]:
def func(s):
    try:
        if s == 0:
            return 0.0
        elif "Гц" in s:
            return float(s.replace("Гц", "").replace(" ", "").replace(",", "."))
        
 
    except Exception:
        pass


df1[column] = df1[column].apply(func)
df2[column] = df2[column].apply(func)

In [167]:
df1[column].unique()

array([ 60.,   0., 120.])

In [168]:
column = 'Цена'

In [169]:
def func(s):
    try:
        if "Нет в наличии" in s:
            return 0.0
        elif "₽" in s:
            return float(s.replace("₽", "").replace(" ", "").replace(",", "."))
        elif "р." in s:
            return int(s.replace("р.", "").replace(" ", ""))
        else:
            return int(s.replace(" ", ""))
 
    except Exception:
        pass



df1[column] = df1[column].apply(func)
df2[column] = df2[column].apply(func)

In [170]:
df2[column]

0          NaN
1      87990.0
2      62990.0
3      77990.0
4      49990.0
        ...   
499    73599.0
500    44999.0
501    47999.0
502    45999.0
503    71999.0
Name: Цена, Length: 504, dtype: float64

In [171]:
df1[column]

0      15990.0
1      17990.0
2      40990.0
3       7490.0
4      94990.0
        ...   
404        0.0
405        0.0
406        0.0
407        0.0
408        0.0
Name: Цена, Length: 409, dtype: float64

In [172]:
column = 'Цвет'

df1[column] = df1[column][df1[column] != 0].str.lower()
df2[column] = df2[column][df2[column] != 0].str.lower()

In [173]:
def func(s):
    try:
        if s == 0:
            return 0.0
        if " " in s:
          return (s.split(" ")[0] + s.split(" ")[1])
        
    except Exception:
        pass



df1[column] = df1[column].apply(func)
df2[column] = df2[column].apply(func)

In [174]:
from sklearn.preprocessing import LabelEncoder


label_encoder = LabelEncoder()


combined_column = pd.concat([df1[column], df2[column]])


label_encoder.fit(combined_column.astype(str))


df1[column] = label_encoder.transform(df1[column].astype(str))
df2[column] = label_encoder.transform(df2[column].astype(str))

In [175]:
df1[column].unique()

array([ 0,  2,  4, 12,  3,  9, 16, 15,  5, 14, 10, 11])

In [176]:
column = 'Рейтинг'

In [177]:
def func(s):
    try:
        if s == 0:
            return 0.0
        
        if "Код товара" in s:
            return 0.0
        elif "Обзор" in s:
            return float(s.split(" Обзор")[0])
        else:
            return float(s)

    except Exception:
        pass



df1[column] = df1[column].apply(func)


In [178]:
df1[column].unique()

array([4.8, 4.3, 4.6, 0. , 4.5, 4.9, 5. , 4. , 4.7, 4.1, 2.5, 3.8, 3.5,
       1. , 3.9, 4.4, 3. ])

In [179]:
df2[column].unique()

array([0., 5., 4., 3., 2.])

In [180]:
column = 'Операционная система'

df1[column] = df1[column][df1[column] != 0].str.lower()
df2[column] = df2[column][df2[column] != 0].str.lower()

In [181]:
def func(s):
    try:
        if s == 0:
            return 0.0
        return (s.split(" ")[0])
    except Exception:
        pass



df1[column] = df1[column].apply(func)
df2[column] = df2[column].apply(func)

In [182]:
from sklearn.preprocessing import LabelEncoder


label_encoder = LabelEncoder()


combined_column = pd.concat([df1[column], df2[column]])


label_encoder.fit(combined_column.astype(str))


df1[column] = label_encoder.transform(df1[column].astype(str))
df2[column] = label_encoder.transform(df2[column].astype(str))



In [183]:
df2[column].head(20)

0     0
1     1
2     1
3     1
4     6
5     6
6     6
7     6
8     6
9     6
10    6
11    6
12    6
13    0
14    0
15    1
16    6
17    6
18    0
19    1
Name: Операционная система, dtype: int32

In [184]:
column = 'Объем оперативной памяти'

In [185]:
def func(s):
    try:
        if s == 0:
            return 0.0
        if "ГБ" in s:
            return float(s.split("ГБ")[0])
    except Exception:
        pass



df1[column] = df1[column].apply(func)
df2[column] = df2[column].apply(func)

In [186]:
df2[column][df2[column] != 0]

15     1.0
22     1.5
25     1.5
31     1.0
41     2.0
45     1.5
46     1.5
48     1.5
118    2.0
162    1.0
164    1.0
175    8.0
182    2.0
183    1.0
186    8.0
187    1.5
212    1.0
213    1.0
217    2.0
227    1.0
229    1.5
231    1.0
244    1.0
245    1.5
251    1.0
252    1.0
265    2.0
268    1.5
274    1.5
275    8.0
276    1.5
292    1.5
294    2.0
302    1.0
303    1.5
308    1.0
323    2.0
328    1.0
330    1.0
332    1.0
335    1.5
336    1.0
340    2.0
341    2.0
345    1.5
351    1.5
373    1.0
375    1.0
411    2.0
416    2.0
417    1.5
433    1.0
453    1.0
454    1.5
487    2.0
Name: Объем оперативной памяти, dtype: float64

In [187]:
def func(s):
    try:
        if s == 0:
            return 0.0
        if "ГБ" in s:
            return int(s.split("ГБ")[0])
    except Exception:
        pass



df1['Объем встроенной памяти'] = df1['Объем встроенной памяти'].apply(func)
df2['Объем встроенной памяти'] = df2['Объем встроенной памяти'].apply(func)


In [188]:
df1['Объем встроенной памяти'][df1['Объем встроенной памяти'] != 0]

0       8.0
6       8.0
8      16.0
9       8.0
14      8.0
       ... 
380     8.0
381     8.0
382     8.0
383     8.0
389     4.0
Name: Объем встроенной памяти, Length: 100, dtype: float64

In [189]:

def func_1(s):
    try :
        if " телевизор" in s:
            return s.split(" телевизор")[0]  +  s.split(" телевизор")[1].split(",")[0]
    except Exception:
        pass

def func_2(s):
    try :
        if "телевизор" in s:
            return s.split("телевизор")[1]
    except Exception:
        pass


df1['Название'] = df1['Название'].apply(func_1)
df2['Название'] = df2['Название'].apply(func_2)



In [190]:
df1['Название'][df1['Название'] != 0]

0          32" haier smart tv s1
1        43" yuno ulx-43utcs3234
2        43" lg 43nano786qa.arub
3         24" bbk 24lem-1089/t2c
4      55" samsung qe55q70bauxce
                 ...            
404    75" hyundai h-led75gu7005
405       24" yuno ulx-24tcsw222
406       55" lg 55nano816pa.aru
407    24" polarline 24pl51tc-sm
408    40" hyundai h-led40et4100
Name: Название, Length: 409, dtype: object

In [191]:
df2['Название'][df2['Название'] != 0]

0                       None
1         65" sony kd-65x75k
2        65" sharp 4t-c65dl6
3       65" sony kd-65x7500h
4         43" lg 43ur81009lk
               ...          
499       65" lg 65uq81006lb
500       43" lg 43ur78009ll
501       50" lg 50ur78009ll
502       43" lg 43ur81009lk
503       55" lg 55ur81009lk
Name: Название, Length: 504, dtype: object

In [192]:

def func(s):
    try :
        if s == 0.0:
            return s
        elif "Mega Contrast" in s:
            return 1000000
        elif "." in s:
            return int(s.split(".")[0] + s.split(".")[1].split(":")[0])
        elif ":" in s:
            return int(s.split(":")[0]) 
    except Exception:
        pass


df1['Контрастность'] = df1['Контрастность'].apply(func)
df2['Контрастность'] = df2['Контрастность'].apply(func)


In [193]:
df2['Контрастность'][df2['Контрастность'] != 0]

15     100000.0
21       1200.0
22       1000.0
23       5000.0
25       1100.0
         ...   
454      5000.0
464      5000.0
488      1200.0
490      1200.0
491      1200.0
Name: Контрастность, Length: 155, dtype: float64

In [194]:
df2['Мощность сабвуфера'][df2['Мощность сабвуфера'].notna()]

0      0
1      0
2      0
3      0
4      0
      ..
499    0
500    0
501    0
502    0
503    0
Name: Мощность сабвуфера, Length: 504, dtype: object

In [195]:

def func(s):
    try :
        if s == 0.0:
            return s
        elif "x" in s:
            return int(s.split("x")[0]) * int(s.split("x")[1].split(" ")[0])
        else:
            return int(s.split(" ")[0])
    except Exception:
        pass


df1['Мощность сабвуфера'] = df1['Мощность сабвуфера'].apply(func)
df2['Мощность сабвуфера'] = df2['Мощность сабвуфера'].apply(func)


In [196]:
df1['Мощность сабвуфера'][df1['Мощность сабвуфера'] > 0]

7      20
34     20
49     20
58     20
115    20
180    20
236    20
278    20
280    20
298    20
305    20
307    10
311    10
312    10
317    20
320    20
343    20
Name: Мощность сабвуфера, dtype: int64

In [197]:
def func(s):
    try :
        if s == 0:
            return 0.0
        elif "кг" in s:
            return float(s.split(" ")[0])

    except Exception:
        pass

df1['Вес без подставки'] = df1['Вес без подставки'].apply(func)
df2['Вес без подставки'] = df2['Вес без подставки'].apply(func)

In [198]:
df1['Вес без подставки'].unique()

array([ 3.7 ,  0.  ,  9.2 , 15.5 ,  4.3 , 19.4 , 14.  , 11.5 , 10.3 ,
        2.5 ,  4.55,  8.8 , 26.  ,  4.  , 13.5 , 19.  , 24.6 ,  5.7 ,
        8.2 , 17.2 , 26.5 , 14.7 , 12.44, 12.5 ,  4.75, 41.  ,  4.1 ,
        7.44,  7.2 , 20.9 ,  3.4 , 38.5 ,  9.94, 17.7 ,  8.1 , 16.  ,
        3.8 , 41.5 , 35.  , 24.8 , 22.4 ,  9.  , 43.8 ,  6.3 ,  2.9 ,
        3.25, 18.2 , 13.43, 24.5 , 45.2 , 10.9 , 24.2 , 30.4 , 31.4 ,
       11.4 , 17.6 , 25.7 , 18.86,  9.32, 11.9 ,  6.5 , 13.7 , 23.2 ,
       27.9 , 16.5 ,  9.5 ,  6.8 , 55.3 , 33.3 , 23.6 , 21.4 , 31.1 ,
       15.  , 16.3 , 21.  , 12.1 , 11.7 , 13.  ,  9.3 ,  8.9 ,  8.  ,
        4.85,  5.4 ,  6.58,  5.6 , 22.7 ,  3.3 ,  3.5 , 19.5 , 38.  ,
        6.2 ,  2.25, 24.7 , 11.8 , 25.1 , 14.8 , 17.8 ,  4.7 , 18.5 ,
       44.2 , 16.7 , 43.3 , 43.1 , 32.1 , 22.6 , 14.5 ,  7.9 , 44.5 ,
       16.1 ,  8.6 ,  8.3 , 14.6 , 26.1 , 12.7 , 10.7 , 18.4 , 12.6 ,
       12.3 , 18.1 ,  2.4 , 14.3 , 40.2 , 11.  ,  6.65,  3.05, 10.4 ,
        7.  ,  4.65,

In [199]:
df2['Встроенный сабвуфер'][df2['Встроенный сабвуфер'] == 1]

117    1.0
120    1.0
128    1.0
130    1.0
209    1.0
211    1.0
244    1.0
277    1.0
296    1.0
318    1.0
358    1.0
393    1.0
401    1.0
418    1.0
421    1.0
430    1.0
435    1.0
436    1.0
437    1.0
439    1.0
446    1.0
458    1.0
459    1.0
461    1.0
471    1.0
496    1.0
497    1.0
498    1.0
Name: Встроенный сабвуфер, dtype: float64

In [200]:
df1['Встроенный сабвуфер'][df1['Встроенный сабвуфер'] == 1]

7      1.0
34     1.0
49     1.0
58     1.0
115    1.0
180    1.0
236    1.0
278    1.0
280    1.0
293    1.0
298    1.0
305    1.0
307    1.0
308    1.0
309    1.0
310    1.0
311    1.0
312    1.0
317    1.0
318    1.0
320    1.0
343    1.0
Name: Встроенный сабвуфер, dtype: float64

In [201]:
def func(s):
    try :
        if s == 0:
            return 0.0
        elif "год" in s:
            return int(s.split(" ")[0])* 12
        elif "мес." in s:
            return int(s.split(" ")[0])


    except Exception:
        pass

df1['Гарантия'] = df1['Гарантия'].apply(func)
df2['Гарантия'] = df2['Гарантия'].apply(func)

In [202]:
df2['Гарантия'][df2['Гарантия'] != 0]

0      12.0
1      12.0
2      12.0
3      12.0
4      12.0
       ... 
499    12.0
500    12.0
501    12.0
502    12.0
503    12.0
Name: Гарантия, Length: 498, dtype: float64

In [203]:
df1['Гарантия'][df1['Гарантия'] > 12]

291    24.0
Name: Гарантия, dtype: float64

In [204]:
def func(s):
    try :
        if s == 0:
            return 0.0
        elif "см" in s:
            return int(s.split("см")[0].split("(")[1])


    except Exception:
        pass

df1['Диагональ'] = df1['Диагональ'].apply(func)
df2['Диагональ'] = df2['Диагональ'].apply(func)

In [205]:
df1['Диагональ'][df1['Диагональ'] != 0]

0       81.0
6      127.0
9      140.0
11     127.0
15      81.0
17     127.0
25     165.0
28     102.0
30     127.0
32     127.0
37     140.0
42      81.0
47     165.0
50     102.0
140    178.0
162     61.0
163     61.0
192    190.0
193    165.0
194    127.0
195    140.0
196    109.0
199    165.0
217    147.0
218    127.0
219     81.0
220    109.0
221    102.0
222     81.0
273    190.0
274    165.0
275     81.0
276     81.0
282    140.0
283    109.0
284    109.0
285    109.0
286     81.0
287    140.0
288     81.0
289     61.0
292    190.0
295    165.0
296    140.0
301     81.0
302     61.0
313    140.0
314    127.0
315    109.0
327    109.0
329    109.0
331     81.0
332     81.0
354    127.0
359     61.0
362    190.0
368    140.0
370    165.0
371    140.0
372    127.0
Name: Диагональ, dtype: float64

In [206]:
df1['Количество отзывов'][df1['Количество отзывов'] != 0]

0      14.0
1       3.0
2       5.0
3       6.0
5      21.0
       ... 
403     1.0
404     1.0
405    32.0
407     8.0
408    21.0
Name: Количество отзывов, Length: 171, dtype: float64

In [207]:
df1.head(10)

Название  Рейтинг  Количество отзывов      Цена  \
0       32" haier smart tv s1      4.8                14.0   15990.0   
1     43" yuno ulx-43utcs3234      4.3                 3.0   17990.0   
2     43" lg 43nano786qa.arub      4.6                 5.0   40990.0   
3      24" bbk 24lem-1089/t2c      4.8                 6.0    7490.0   
4   55" samsung qe55q70bauxce      0.0                 0.0   94990.0   
5   32" hyundai h-led32et3021      4.5                21.0    9440.0   
6  50" starwind sw-led50ug400      4.5                 4.0   25390.0   
7          55" hisense 55u8hq      4.9                14.0  124990.0   
8              65" tcl 65p637      5.0                12.0   47990.0   
9  55" starwind sw-led55ug400      4.0                 3.0   28290.0   

  Страна производитель     Бренд         Модель  Диагональ   Разрешение  \
0               Россия     HAIER    Smart TV S1       81.0  1920 x 1080   
1                    0      YUNO              0        0.0            0   
2                    0        LG              0        0.0            0   
3                    0       BBK              0        0.0            0   
4                    0   SAMSUNG              0        0.0            0   
5                    0   HYUNDAI              0        0.0            0   
6             Беларусь  STARWIND  SW-LED50UG400      127.0  3840 x 2160   
7                    0   HISENSE              0        0.0            0   
8                    0       TCL              0        0.0            0   
9             Беларусь  STARWIND  SW-LED55UG400      140.0  3840 x 2160   

  Соотношение сторон Тип панели Яркость экрана  Контрастность  \
0               16:9        LED      220 кд/м2           4000   
1                  0          0              0              0   
2                  0          0              0              0   
3                  0          0              0              0   
4                  0          0              0              0   
5                  0          0              0              0   
6               16:9        LED      250 кд/м2           6000   
7                  0          0              0              0   
8                  0          0              0              0   
9               16:9        LED      250 кд/м2           5000   

  Время отклика пикселя                           Углы обзора  \
0                6.5 мс  178 по горизонтали, 178 по вертикали   
1                     0                                     0   
2                     0                                     0   
3                     0                                     0   
4                     0                                     0   
5                     0                                     0   
6                  8 мс  178 по горизонтали, 178 по вертикали   
7                     0                                     0   
8                     0                                     0   
9                6.5 мс  178 по горизонтали, 178 по вертикали   

   Частота обновления Тип подсветки Безрамочный дизайн  Цифровой тюнер DVB-T2  \
0                60.0         D-LED                 да                    1.0   
1                 0.0             0                  0                    1.0   
2                 0.0             0                  0                    1.0   
3                 0.0             0                  0                    1.0   
4                 0.0             0                  0                    1.0   
5                 0.0             0                  0                    1.0   
6                60.0             0                  0                    1.0   
7                 0.0             0                  0                    1.0   
8                 0.0             0                  0                    1.0   
9                60.0             0                  0                    1.0   

   Цифровой тюнер DVB-T  Кабельный тюнер DVB-C  Спутниковый тюнер DVB-S2  \
0 

In [208]:
df2.head(10)

Название     Цена  Рейтинг  Количество отзывов    Страна  \
0                   None      NaN      0.0                 0.0  Беларусь   
1     65" sony kd-65x75k  87990.0      0.0                 0.0   Вьетнам   
2    65" sharp 4t-c65dl6  62990.0      0.0                 0.0    Египет   
3   65" sony kd-65x7500h  77990.0      0.0                 0.0  Малайзия   
4     43" lg 43ur81009lk  49990.0      0.0                 0.0    Польша   
5     43" lg 43ur78006lk  44990.0      0.0                 0.0    Польша   
6     43" lg 43uq81006lb  39390.0      0.0                 0.0    Польша   
7     43" lg 43ur91006la  52990.0      0.0                 0.0    Польша   
8     43" lg 43uq75006lf  30990.0      0.0                 0.0    Польша   
9     43" lg 43ur81006lj  49990.0      0.0                 0.0    Польша   

   Гарантия  Операционная система Потребляемая мощность  Диагональ Технология  \
0      12.0                     0                     0       61.0       LED    
1      12.0                     1                135 Вт        NaN       LED    
2      12.0                     1                224 Вт        NaN       LED    
3      12.0                     1                135 Вт        NaN       LED    
4      12.0                     6                110 Вт        NaN       LED    
5      12.0                     6                115 Вт        NaN       LED    
6      12.0                     6                100 Вт        NaN       LED    
7      12.0                     6                 88 Вт        NaN       LED    
8      12.0                     6                100 Вт        NaN       LED    
9      12.0                     6                110 Вт        NaN       LED    

               Разрешение экрана  Поддержка HDR  \
0      1366x768 Пикс (HD-Ready)             0.0   
1  3840x2160 Пикс (4K Ultra HD)             1.0   
2  3840x2160 Пикс (4K Ultra HD)             1.0   
3  3840x2160 Пикс (4K Ultra HD)             1.0   
4  3840x2160 Пикс (4K Ultra HD)             1.0   
5  3840x2160 Пикс (4K Ultra HD)             1.0   
6  3840x2160 Пикс (4K Ultra HD)             1.0   
7  3840x2160 Пикс (4K Ultra HD)             1.0   
8  3840x2160 Пикс (4K Ultra HD)             1.0   
9  3840x2160 Пикс (4K Ultra HD)             1.0   

   Воспроизведение видео через USB  Smart TV Управление  Таймер выключения  \
0                              1.0       0.0          0                1.0   
1                              1.0       1.0   Голосом                 1.0   
2                              1.0       1.0   Голосом                 1.0   
3                              1.0       1.0   Голосом                 1.0   
4                              1.0       1.0   Голосом                 1.0   
5                              1.0       1.0   Голосом                 1.0   
6                              1.0       1.0   Голосом                 1.0   
7                              1.0       1.0   Голосом                 1.0   
8                              1.0       1.0   Голосом                 1.0   
9                              1.0       1.0   Голосом                 1.0   

   Часы  Защита от детей  Телетекст  Функция TimeShift  \
0   1.0              1.0        1.0                0.0   
1   0.0              1.0        0.0                1.0   
2   0.0              1.0        0.0                1.0   
3   0.0              1.0        1.0                1.0   
4   0.0              1.0        1.0                1.0   
5   0.0              1.0        0.0                1.0   
6   0.0              1.0        0.0                1.0   
7   0.0              1.0        0.0                1.0   
8   0.0              1.0        1.0                1.0   
9   0.0              1.0        0.0                1.0   

   Запись телепередач (PVR)  Разъем для модуля DVB CAM (слот CI)  \
0                       0.0                                  1.0   
1                       1.0                                  1.0   
2                      

In [209]:
df2.rename(columns={'Страна': 'Страна производитель'}, inplace=True)

In [210]:
df2.rename(columns={'Стандарт VESA': 'Размер VESA'}, inplace=True)

In [211]:
df2.rename(columns={'Разрешение экрана': 'Разрешение'}, inplace=True)

In [212]:
df2.rename(columns={'Формат': 'Соотношение сторон'}, inplace=True)

In [213]:
df2.rename(columns={'Технология': 'Тип панели'}, inplace=True)

In [214]:
df2.rename(columns={'Яркость': 'Яркость экрана'}, inplace=True)

In [215]:
name_old = 'Время отклика'
name_new = 'Время отклика пикселя'
df2.rename(columns={name_old: name_new}, inplace=True)

In [216]:
name_old = 'Тип подсветки'
name_new = 'Тип светодиодной подсветки'
df2.rename(columns={name_old: name_new}, inplace=True)

In [217]:
name_old = 'Wi-Fi'
name_new = 'Встроенный Wi-Fi'
df2.rename(columns={name_old: name_new}, inplace=True)

In [218]:
name_old = 'Bluetooth'
name_new = 'Встроенный Bluetooth'
df2.rename(columns={name_old: name_new}, inplace=True)

In [219]:
name_old = 'Таймер выключения'
name_new = 'Таймер включения/выключения'
df2.rename(columns={name_old: name_new}, inplace=True)

In [220]:
name_old = 'SMART TV'
name_new = 'Поддержка SMART TV'
df2.rename(columns={name_old: name_new}, inplace=True)

In [221]:
name_old = 'Смартфон в качестве пульта ДУ'
name_new = 'Управление со смартфона'
df2.rename(columns={name_old: name_new}, inplace=True)

In [222]:
name_old = 'Выход для наушников'
name_new = 'Разъем для наушников'
df2.rename(columns={name_old: name_new}, inplace=True)

In [223]:
name_old = 'NFC'
name_new = 'Поддержка NFC'
df2.rename(columns={name_old: name_new}, inplace=True)

In [224]:
name_old = 'Картинка в картинке (PIP)'
name_new = 'Картинка в картинке (PIP)'
df2.rename(columns={name_old: name_new}, inplace=True)

In [225]:
columns1 = df1.columns
columns2 = df2.columns

In [226]:
column = set(columns1) & set(columns2)

In [227]:
df_full = df1.loc[:, column]

C:\Users\ilya\AppData\Local\Temp\ipykernel_13808\1887247473.py:1: FutureWarning: Passing a set as an indexer is deprecated and will raise in a future version. Use a list instead.
  df_full = df1.loc[:, column]


In [228]:
column = 'Разрешение'

In [229]:
def func(s):
    try:
        if s == 0:
            return 0.0
        if 'Пикс' in s:
            return s.split(' Пикс')[0]
        elif ' x ' in s:
            return s.split(' x ')[0] + 'x' + s.split(' x ')[1] 

        elif '2160' in s:
            return '3840x' + '2160'  
        return s
    except Exception:
        pass




df1[column] = df1[column].apply(func)
df2[column] = df2[column].apply(func)

In [230]:
from sklearn.preprocessing import LabelEncoder


label_encoder = LabelEncoder()


combined_column = pd.concat([df1[column], df2[column]])


label_encoder.fit(combined_column.astype(str))


df1[column] = label_encoder.transform(df1[column].astype(str))
df2[column] = label_encoder.transform(df2[column].astype(str))

In [231]:
df2[column].unique()

array([1, 3, 2, 0, 4])

In [232]:
df1[column].unique()

array([2, 0, 3, 1])

In [233]:
column = 'Тип панели'

In [234]:
def func(s):
    try:
        if ' ' in s:
            return s.replace(' ', '')

        return s
    except Exception:
        pass




df1[column] = df1[column].apply(func)
df2[column] = df2[column].apply(func)

In [235]:
from sklearn.preprocessing import LabelEncoder


label_encoder = LabelEncoder()


combined_column = pd.concat([df1[column], df2[column]])


label_encoder.fit(combined_column.astype(str))


df1[column] = label_encoder.transform(df1[column].astype(str))
df2[column] = label_encoder.transform(df2[column].astype(str))

In [236]:
df2[column].unique()

array([ 3,  9,  8,  7,  4,  6, 11, 10,  0,  5,  2])

In [237]:
df1[column].unique()

array([3, 6, 8, 7, 1])

In [238]:
column = 'Страна производитель'

In [239]:
def func(s):
    try:
        if 'РФ' in s:
            return 'Россия'

        return s
    except Exception:
        pass




df1[column] = df1[column].apply(func)
df2[column] = df2[column].apply(func)

In [240]:
from sklearn.preprocessing import LabelEncoder


label_encoder = LabelEncoder()


combined_column = pd.concat([df1[column], df2[column]])


label_encoder.fit(combined_column.astype(str))


df1[column] = label_encoder.transform(df1[column].astype(str))
df2[column] = label_encoder.transform(df2[column].astype(str))

In [241]:
df2[column].unique()

array([ 2,  5,  7, 11, 12, 10, 16, 13,  8, 15,  3,  0, 17, 14,  1,  6,  4,
        9])

In [242]:
df1[column].unique()

array([13,  0,  2, 10])

In [243]:
column = 'Акустическая схема'

In [244]:
def func(s):
    try:
        if s == 0:
            return 0.0
        elif s.count('.') == 2:
            return int(s.split('.')[0])
    except Exception:
        pass

    try:
        if s == 0:
            return 0.0
        else:
            return round(s)
    except Exception:
        pass

    



df1[column] = df1[column].apply(func)
df2[column] = df2[column].apply(func)

In [245]:
from sklearn.preprocessing import LabelEncoder


label_encoder = LabelEncoder()


combined_column = pd.concat([df1[column], df2[column]])


label_encoder.fit(combined_column.astype(str))


df1[column] = label_encoder.transform(df1[column].astype(str))
df2[column] = label_encoder.transform(df2[column].astype(str))

In [246]:
df2[column].unique()

array([0, 1, 2])

In [247]:
df1[column][df1[column]].unique()

array([0, 4])

In [248]:
column = 'Соотношение сторон'

In [249]:
from sklearn.preprocessing import LabelEncoder


label_encoder = LabelEncoder()


combined_column = pd.concat([df1[column], df2[column]])


label_encoder.fit(combined_column.astype(str))


df1[column] = label_encoder.transform(df1[column].astype(str))
df2[column] = label_encoder.transform(df2[column].astype(str))

In [250]:
df2[column][df2[column] != 0 ].unique()

array([1, 2])

In [251]:
df1[column][df1[column] != 0 ].unique()

array([1])

In [252]:
column = 'Яркость экрана'

In [253]:
def func(s):
    try:
        if s == 0:
            return 0.0
        if "кд" in s:
            return float(s.split("кд")[0])
        else:
            return s
    except Exception:
        pass



df1[column] = df1[column].apply(func)
df2[column] = df2[column].apply(func)

In [254]:
df2[column][df2[column] != 0 ].unique()

array([ 220.,  250.,  240.,  350.,  200.,  320.,  500.,  260.,  300.,
        280.,  230., 1000.,  150.,  380.,  270.,  210.,  180.,  800.,
        310.,  370.,  400., 1200.])

In [255]:
df1[column][df1[column] != 0 ].unique()

array([ 220.,  250.,  200.,  350.,  400.,  280.,  320., 1000.,  300.,
        230.])

In [256]:
column = 'Время отклика пикселя'

In [257]:
def func(s):
    try:
        if "мс" in s:
            return float(s.replace(" мс", ""))
        else:
            return s
    except Exception:
        pass



df1[column] = df1[column].apply(func)
df2[column] = df2[column].apply(func)

In [258]:
df2[column][df2[column] != 0 ].unique()

array([ nan,  8.5,  6. ,  8. ,  6.5,  1. ,  9.5, 11.5,  7. ,  3. ,  9. ,
        5. ,  0.1])

In [259]:
df1[column][df1[column] != 0 ].unique()

array([ 6.5,  nan,  8. ,  8.5,  9.5,  1. , 11.5,  5. ])

In [260]:
column = 'Размер VESA'

In [261]:
def func(s):
    try:
        if " " in s:
            return (s.replace(" ", ""))
        else:
            return s
    except Exception:
        pass



df1[column] = df1[column].apply(func)
df2[column] = df2[column].apply(func)

In [262]:
from sklearn.preprocessing import LabelEncoder


label_encoder = LabelEncoder()


combined_column = pd.concat([df1[column], df2[column]])


label_encoder.fit(combined_column.astype(str))


df1[column] = label_encoder.transform(df1[column].astype(str))
df2[column] = label_encoder.transform(df2[column].astype(str))

In [263]:
df1[column][df1[column] != 0 ].unique()


array([ 2,  3, 12,  9,  8,  4,  6,  7, 14, 11, 10,  5, 15])

In [264]:
column = set(df1.columns) & set(df2.columns)

In [265]:
df_full = df1.loc[:, column]

C:\Users\ilya\AppData\Local\Temp\ipykernel_13808\1887247473.py:1: FutureWarning: Passing a set as an indexer is deprecated and will raise in a future version. Use a list instead.
  df_full = df1.loc[:, column]


In [266]:
df_full.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 409 entries, 0 to 408
Data columns (total 34 columns):
 #   Column                       Non-Null Count  Dtype  
---  ------                       --------------  -----  
 0   Цена                         409 non-null    float64
 1   Акустическая схема           409 non-null    int32  
 2   Таймер включения/выключения  409 non-null    float64
 3   Разъем для наушников         409 non-null    float64
 4   Встроенный сабвуфер          409 non-null    float64
 5   Прогрессивная развертка      409 non-null    float64
 6   Вес без подставки            409 non-null    float64
 7   Время отклика пикселя        56 non-null     float64
 8   Гарантия                     409 non-null    float64
 9   Разрешение                   409 non-null    int32  
 10  Поддержка NFC                409 non-null    float64
 11  Управление со смартфона      409 non-null    float64
 12  Встроенный Wi-Fi             409 non-null    float64
 13  Встроенный Bluetooth

In [267]:
df1['Количество отзывов'] = pd.DataFrame({'Количество отзывов': np.random.normal(loc=10, scale=5, size=100)}).round(0)
df2['Количество отзывов'] = pd.DataFrame({'Количество отзывов': np.random.normal(loc=10, scale=5, size=100)}).round(0)

df1['Количество отзывов'] = df1['Количество отзывов'].clip(1, 30)
df1['Количество отзывов'] = df1['Количество отзывов'].clip(1, 30)

In [268]:
df1 = df1.fillna(0)
df2 = df2.fillna(0)

In [269]:
df1 = df1.loc[:, column]
df2 = df2.loc[:, column]

df1.to_csv(f'data_citilink.csv', index=False)
df2.to_csv(f'data_eldorado.csv', index=False)

C:\Users\ilya\AppData\Local\Temp\ipykernel_13808\1496648104.py:1: FutureWarning: Passing a set as an indexer is deprecated and will raise in a future version. Use a list instead.
  df1 = df1.loc[:, column]
C:\Users\ilya\AppData\Local\Temp\ipykernel_13808\1496648104.py:2: FutureWarning: Passing a set as an indexer is deprecated and will raise in a future version. Use a list instead.
  df2 = df2.loc[:, column]
