In [2669]:
from selenium import webdriver
import numpy as np

import time
from selenium import webdriver

from selenium.webdriver.common.by import By

from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support.expected_conditions import presence_of_element_located

from selenium.webdriver.support import expected_conditions
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
import time
from selenium import webdriver
from selenium.webdriver.chrome.service import Service
import pandas as pd

In [2670]:
from sklearn.preprocessing import LabelEncoder


label_encoder = LabelEncoder()

In [2671]:

pd.set_option('display.max_columns', None)

In [2672]:

pd.set_option('display.max_rows', None)

In [2673]:
df1 = pd.read_csv(r'A:\Учёба\практика 2 курс\data\citilink/pk/data.csv')
df2 = pd.read_csv(r'A:\Учёба\практика 2 курс\data\eldorado/pk/data.csv')

In [2674]:
df1.replace("есть", 1, inplace=True)
df2.replace("есть", 1, inplace=True)

df1.replace("да", 1, inplace=True)
df2.replace("да", 1, inplace=True)

df1.replace("нет", 1, inplace=True)
df2.replace("нет", 1, inplace=True)

df1.replace("Нет", 1, inplace=True)
df2.replace("Нет", 1, inplace=True)

df1.replace("Есть ", 1, inplace=True)
df2.replace("Есть ", 1, inplace=True)

df1.replace("Есть", 1, inplace=True)
df2.replace("Есть", 1, inplace=True)

In [2675]:
df1 = df1.fillna(0)
df2 = df2.fillna(0)

In [2676]:
columns1 = df1.columns
columns2 = df2.columns

In [2677]:
set(columns1) & set(columns2)

{'link',
 'Гарантия',
 'Клавиатура',
 'Количество отзывов',
 'Мышь',
 'Название',
 'Операционная система',
 'Разъем для микрофона',
 'Разъем для наушников',
 'Рейтинг',
 'Стандарт Wi-Fi',
 'Тип вилки',
 'Цена'}

In [2678]:
df1[df1.ne(0)].count().sort_values(ascending=False)


link                                      428
Название                                  428
Цена                                      428
Рейтинг                                   421
Гарантийное                               397
Гарантия                                  397
Цвет корпуса                              397
Операционная система                      396
Тип графического контроллера              394
Тип кабельной сети (разъем RJ-45)         394
Процессор                                 394
Вес упаковки (ед)                         394
Оперативная память                        394
Количество ядер процессора                394
Размеры корпуса (ШхВхГ)                   393
Разъемов USB 3.0                          393
Бренд                                     391
Процессор, частота                        388
Графика                                   387
Разъемов HDMI                             385
Габариты упаковки (ед) ДхШхВ              383
Объем SSD                         

In [2679]:
df1['Графика']

0           NVIDIA GeForce RTX 3060 - 12288 Мб
1                       Intel UHD Graphics 630
2                                            0
3                       Intel UHD Graphics 630
4            NVIDIA GeForce RTX 3050 - 8192 Мб
5          NVIDIA GeForce RTX 3060Ti - 8192 Мб
6      NVIDIA GeForce GTX 1660 Super - 6144 Мб
7      NVIDIA GeForce GTX 1660 Super - 6144 Мб
8            NVIDIA GeForce RTX 3050 - 8192 Мб
9            NVIDIA GeForce GTX 1650 - 4096 Мб
10                                           0
11                      Intel UHD Graphics 610
12                      Intel UHD Graphics 730
13           NVIDIA GeForce GTX 1650 - 4096 Мб
14                         AMD Radeon Graphics
15                      Intel UHD Graphics 610
16                         AMD Radeon Graphics
17                      Intel UHD Graphics 730
18                      Intel UHD Graphics 730
19          NVIDIA GeForce RTX 3060 - 12288 Мб
20             NVIDIA GeForce GT1030 - 2048 Мб
21           

In [2680]:
df1['Оперативная память']

0         16 ГБ, DDR4, DIMM, 3200 МГц
1          8 ГБ, DDR4, DIMM, 2666 МГц
2                                   0
3         16 ГБ, DDR4, DIMM, 2666 МГц
4         16 ГБ, DDR4, DIMM, 3200 МГц
5         16 ГБ, DDR4, DIMM, 2933 МГц
6         16 ГБ, DDR4, DIMM, 3200 МГц
7         16 ГБ, DDR4, DIMM, 3200 МГц
8         16 ГБ, DDR4, DIMM, 3200 МГц
9                    8 ГБ, DDR4, DIMM
10                                  0
11         8 ГБ, DDR4, DIMM, 2666 МГц
12         8 ГБ, DDR4, DIMM, 2666 МГц
13        16 ГБ, DDR4, DIMM, 3200 МГц
14         8 ГБ, DDR4, DIMM, 3200 МГц
15         4 ГБ, DDR4, DIMM, 2400 МГц
16        16 ГБ, DDR4, DIMM, 3200 МГц
17         8 ГБ, DDR4, DIMM, 2666 МГц
18         8 ГБ, DDR4, DIMM, 3200 МГц
19        16 ГБ, DDR4, DIMM, 2666 МГц
20         8 ГБ, DDR4, DIMM, 3200 МГц
21     16 ГБ, DDR4, SO-DIMM, 2666 МГц
22                    , DDR4, SO-DIMM
23                              16 ГБ
24        16 ГБ, DDR4, DIMM, 3200 МГц
25         8 ГБ, DDR4, DIMM, 2666 МГц
26         8

In [2681]:
df2['Модель процессора']

0           Core i5-12400
1           Core i5-12400
2           Ryzen 5 5600X
3          Core i5-11400F
4           Core i3-10105
5        Ryzen 5 Pro 3600
6          Core i5-11400F
7          Core i5-12400F
8          Core i5-11400F
9          Core i5-11400F
10         Core i5-11400F
11         Core i5-11400F
12           Ryzen 5 3600
13           Athlon 3050U
14          Ryzen 3 3250U
15               A4-9120e
16          Core i5-12400
17          Core i5-12400
18          Core i5-10400
19         Core i5-11400F
20         Core i5-11400F
21          Ryzen 5 5600G
22          Core i5-11400
23         Core i5-10400F
24           Ryzen 5 3600
25         Core i5-11400F
26         Core i5-10400F
27         Core i3-10105F
28         Core i5-11400F
29          Ryzen 5 3400G
30          Core i3-10105
31           Ryzen 5 3600
32         Core i5-11400F
33           Ryzen 5 3600
34         Core i7-11700F
35         Core i5-11400F
36         Core i7-11700F
37         Core i5-10400F
38         C

In [2682]:
set(columns1)

{'link',
 'Блок питания',
 'Бренд',
 'Буферная память HDD',
 'Вес товара',
 'Вес упаковки (ед)',
 'Возможность монтажа в стойку',
 'Время отклика',
 'Встроенные динамики',
 'Входное напряжение (макс)',
 'Входное напряжение (мин)',
 'Габариты упаковки (ед) ДхШхВ',
 'Гарантийное',
 'Гарантия',
 'Графика',
 'Диагональ экрана',
 'Дополнительно в комплекте',
 'Жесткий диск',
 'Кард-ридер',
 'Клавиатура',
 'Клавиатура с русскими буквами',
 'Количество высокопроизводительных ядер',
 'Количество отзывов',
 'Количество энергоэффективных ядер',
 'Количество ядер процессора',
 'Комплектация',
 'Максимальный объем оперативной памяти',
 'Модель монитора',
 'Монитор в комплекте',
 'Мышь',
 'Название',
 'Объем SSD',
 'Объем второго SSD',
 'Оперативная память',
 'Операционная система',
 'Оптический привод',
 'Особенности',
 'Особенности ОС',
 'Особенности графического контроллера',
 'Особенности жестких дисков',
 'Особенности оперативной памяти',
 'Особенности процессора',
 'Отделка корпуса',
 'Поддер

In [2683]:
set(columns2)

{'Bluetooth-адаптер',
 'DVI',
 'DisplayPort',
 'HDMI',
 'LAN разъем (RJ-45)',
 'LAN-адаптер',
 'Line-In',
 'PS/2',
 'Speaker-Out',
 'Thunderbolt 3',
 'Thunderbolt/USB 4',
 'Toslink',
 'USB',
 'USB 2.0',
 'USB 3.0',
 'USB 3.0 (Type-C)',
 'USB 3.1',
 'USB 3.1 (Type-C)',
 'USB 3.2',
 'USB 3.2 (Type-C)',
 'VGA (D-Sub)',
 'Wi-Fi',
 'link',
 'Вес',
 'Высота',
 'Гарантия',
 'Глубина',
 'Дополнительная информация',
 'Звуковая карта',
 'Игровой системный блок',
 'Интерфейс подключения',
 'Кабель питания',
 'Картридер',
 'Клавиатура',
 'Количество отзывов',
 'Количество ядер',
 'Количество ядер графического процессора',
 'Кэш L2',
 'Кэш L3',
 'Максимальная тактовая частота',
 'Максимальный объем',
 'Материал корпуса',
 'Модель видеокарты',
 'Модель процессора',
 'Модель чипсета',
 'Мощность блока питания',
 'Мышь',
 'Название',
 'Объем видеопамяти',
 'Объем второго накопителя',
 'Объем накопителя',
 'Объем оперативной памяти',
 'Объем первого накопителя',
 'Операционная система',
 'Подсветка кор

In [2684]:


name_old = 'Количество ядер процессора'
name_new = 'Количество ядер'
df1.rename(columns={name_old: name_new}, inplace=True)

In [2685]:

name_old = 'Модель процессора'
name_new = 'Процессор'
df2.rename(columns={name_old: name_new}, inplace=True)

In [2686]:
 
name_old = 'Объем накопителя'
name_new = 'Объем SSD'
df2.rename(columns={name_old: name_new}, inplace=True)

In [2687]:

name_old = 'Модель видеокарты'
name_new = 'Графика'
df2.rename(columns={name_old: name_new}, inplace=True)

In [2688]:

name_old = 'Количество потоков'
name_new = 'Максимальное число потоков'
df2.rename(columns={name_old: name_new}, inplace=True)

In [2689]:
name_old = 'Мощность блока питания'
name_new = 'Блок питания'
df2.rename(columns={name_old: name_new}, inplace=True)

In [2690]:

name_old = 'Количество слотов'
name_new = 'Количество слотов оперативной'
df2.rename(columns={name_old: name_new}, inplace=True)

In [2691]:

name_old = 'Картридер'
name_new = 'Кард-ридер'
df2.rename(columns={name_old: name_new}, inplace=True)

In [2692]:
name_old = 'Web-камера'
name_new = 'Веб-камера'
df2.rename(columns={name_old: name_new}, inplace=True)

In [2693]:
name_old = 'USB 2.0 (Type-C)'
name_new = 'Порты USB 2.1 (Type-C)'
df2.rename(columns={name_old: name_new}, inplace=True)

In [2694]:
name_old = 'Оперативная память'
name_new = 'Объем оперативной памяти'
df1.rename(columns={name_old: name_new}, inplace=True)

In [2695]:
name_old = 'USB 3.0 (Type-C)'
name_new = 'Порты USB 3.0 (Type-C)'
df2.rename(columns={name_old: name_new}, inplace=True)

In [2696]:
name_old = 'USB 3.1 (Type-C)'
name_new = 'Порты USB 3.1 (Type-C)'
df2.rename(columns={name_old: name_new}, inplace=True)

In [2697]:
name_old = 'USB 3.2 (Type-C)'
name_new = 'Порты USB 3.2 (Type-C)'
df2.rename(columns={name_old: name_new}, inplace=True)

In [2698]:

name_old = 'Мощность блока питания'
name_new = 'Выходная мощность адаптера питания'
df2.rename(columns={name_old: name_new}, inplace=True)

In [2699]:


name_old = 'Диагональ экрана в'
name_new = 'Диагональ экрана'
df1.rename(columns={name_old: name_new}, inplace=True)

In [2700]:

name_old = 'Технология динамического экрана'
name_new = 'Динамический экран'
df2.rename(columns={name_old: name_new}, inplace=True)

In [2701]:

name_old = 'Игровой ноутбук'
name_new = 'Для геймеров'
df2.rename(columns={name_old: name_new}, inplace=True)

In [2702]:
df1 = df1.fillna(0)
df2 = df2.fillna(0)

In [2703]:
column = set(df1.columns) & set(df2.columns)

df_full = df1.loc[:, column]

df_full.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 428 entries, 0 to 427
Data columns (total 20 columns):
 #   Column                    Non-Null Count  Dtype  
---  ------                    --------------  -----  
 0   Процессор                 428 non-null    object 
 1   Гарантия                  428 non-null    object 
 2   Объем SSD                 428 non-null    object 
 3   Кард-ридер                428 non-null    object 
 4   Мышь                      428 non-null    object 
 5   Цена                      428 non-null    object 
 6   Количество ядер           428 non-null    object 
 7   Стандарт Wi-Fi            428 non-null    object 
 8   Количество отзывов        428 non-null    float64
 9   Название                  428 non-null    object 
 10  Операционная система      428 non-null    object 
 11  Клавиатура                428 non-null    object 
 12  link                      428 non-null    object 
 13  Рейтинг                   428 non-null    object 
 14  Блок питан

C:\Users\ilya\AppData\Local\Temp\ipykernel_11888\3155891446.py:3: FutureWarning: Passing a set as an indexer is deprecated and will raise in a future version. Use a list instead.
  df_full = df1.loc[:, column]


In [2704]:
column = 'Блок питания'

In [2705]:
def func(s):
    try:
        if " Вт" in s:
          return float(s.replace(" Вт", ""))
        
        return s
        
    except Exception:
        pass



df1[column] = df1[column].apply(func)
df2[column] = df2[column].apply(func)

In [2706]:
print(df1[column][df1[column] != 0 ].unique())
print(df2[column][df2[column] != 0 ].unique())

[ 650.  400.  500.  330.   nan  700.  300.   65.  120.   90.  750.  100.
  550.  800.  350.  180.  280.  260.  450.  135.  850.  310.  380.  600.
  230.  250. 1000.]
[ 300.  600.   nan  800.  500.  700.  180.   90.   65.  400.  550.  450.
  650. 1000.  750.  185. 1200.   19.  696.  260.  850.  150.  200. 1650.
  380.  310.  370.  230.  120.  350.]


In [2707]:
column = 'Цена'

In [2708]:
def func(s):
    try:
        if "Нет в наличии" in s:
            return 0.0
        elif "₽" in s:
            return float(s.replace("₽", "").replace(" ", "").replace(",", "."))
        elif "р." in s:
            return int(s.replace("р.", "").replace(" ", ""))
        else:
            return int(s.replace(" ", ""))
 
    except Exception:
        pass



df1[column] = df1[column].apply(func)
df2[column] = df2[column].apply(func)

In [2709]:
column = 'Операционная система'

df1[column] = df1[column].str.lower()
df2[column] = df2[column].str.lower()

In [2710]:
def func(s):
    try:
        if s == 0:
            return 0.0
        if "macos" in s:
            return "mac"
        elif " " in s:
            return s.split(" ")[0]
        else:
            return s
    except Exception:
        pass
df1[column] = df1[column].apply(func)
df2[column] = df2[column].apply(func)

In [2711]:
combined_column = pd.concat([df1[column], df2[column]])


label_encoder.fit(combined_column.astype(str))


df1[column] = label_encoder.transform(df1[column].astype(str))
df2[column] = label_encoder.transform(df2[column].astype(str))

In [2712]:
print(df1[column][df1[column] != 0 ].unique())
print(df2[column][df2[column] != 0 ].unique())

[3 7 6 8 5 2]
[9 4 8 6 1 5]


In [2713]:
column = 'Объем оперативной памяти'

In [2714]:
def func(s):
    try:
        if s == 0:
            return 0.0
        if " ГБ" in s:
            return float(s.split(" ГБ")[0])
        else:
            return 0.0
    except Exception:
        pass
df1[column] = df1[column].apply(func)
df2[column] = df2[column].apply(func)

In [2715]:
print(df1[column][df1[column] != 0 ].unique())
print(df2[column][df2[column] != 0 ].unique())

[16.  8.  4. 32. 12.]
[ 16.  32.   8.   4.  64. 128.]


In [2716]:
column = 'Количество ядер'

In [2717]:
def func(s):
    try:
        if s == 0:
            return 0.0
        
        if "-ядерный" in s:
            return float(s.split("-ядерный")[0])
        else:
            return float(s)

    except Exception:
        pass



df1[column] = df1[column].apply(func)

In [2718]:
print(df1[column][df1[column] != 0 ].unique())
print(df2[column][df2[column] != 0 ].unique())

[ 6.  4.  2.  8. 12. 10. 16.]
[ 6.  4.  2.  8. 12. 10. 16. 24. 14.]


In [2719]:
column = 'Рейтинг'

In [2720]:
def func(s):
    try:
        if s == 0:
            return 0.0
        
        if "Код товара" in s:
            return 0.0
        elif "Обзор" in s:
            return float(s.split(" Обзор")[0])
        else:
            return float(s)

    except Exception:
        pass



df1[column] = df1[column].apply(func)

In [2721]:
print(df2[column][df2[column] != 0 ].unique())
print(df1[column][df1[column] != 0 ].unique())

[5. 4. 1.]
[4.8 4.7 5.  4.6 4.5 3.8 3.  4.  4.3 1. ]


In [2722]:
column = 'Гарантия'

In [2723]:
def func(s):
    try :
        if s == 0:
            return 0.0
        elif "год" in s:
            return int(s.split(" ")[0])* 12
        elif "мес." in s:
            return int(s.split(" ")[0])


    except Exception:
        pass

df1[column] = df1[column].apply(func)
df2[column] = df2[column].apply(func)

In [2724]:
print(df2[column][df2[column] != 0 ].unique())
print(df1[column][df1[column] != 0 ].unique())

[12. nan 36. 24.]
[36. 12.]


In [2725]:
column = 'Графика'

df1[column] = df1[column].str.lower()
df2[column] = df2[column].str.lower()

In [2726]:
def func(s):
    try:
        if "nvidia" in s:
            return s.split(" - ")[0].replace("nvidia ", "")
        else:
            return s
    except Exception:
        pass

df1[column] = df1[column].apply(func)

In [2727]:
from sklearn.preprocessing import LabelEncoder


label_encoder = LabelEncoder()


combined_column = pd.concat([df1[column], df2[column]])


label_encoder.fit(combined_column.astype(str))


df1[column] = label_encoder.transform(df1[column].astype(str))
df2[column] = label_encoder.transform(df2[column].astype(str))

In [2728]:
df1[column][df1[column] != 0 ].unique()

array([25, 49,  1, 24, 27, 19, 16, 48, 51,  2, 11, 46, 15, 42, 30, 47, 52,
        7, 18, 53, 31, 43,  4, 28, 14, 12, 50, 71, 45, 21, 33, 44,  3,  6,
       23,  8,  5, 36, 37])

In [2729]:
df2[column][df2[column] != 0 ].unique()

array([16, 25, 68, 41, 28, 67, 66, 65, 57, 56, 58, 24, 76, 22, 60, 74, 59,
       19, 26,  2, 77, 29, 55, 31, 33, 10, 62, 38, 54, 70, 64, 35, 34, 36,
       32,  9, 49, 20, 61, 17, 40, 13, 72, 73, 37, 63, 75, 69, 39])

In [2730]:
column = 'Название'

df1[column] = df1[column].str.lower()
df2[column] = df2[column].str.lower()

In [2731]:
def func(s):
    try:
        if "," in s:
            return s.split(",")[0]
        elif "/" in s:
            return s.split("/")[0]
        else:
            return s
    except Exception:
        pass



df1[column] = df1[column].apply(func)
df2[column] = df2[column].apply(func)

In [2732]:
df1[column][df1[column] != 0 ].head(10)

0              компьютер iru game 310h5gma
1               компьютер iru home 310h5se
2               компьютер iru game 310h5gs
3               компьютер iru home 310h5se
4                                        ‌
5        компьютер hp pavilion tg01-2017ur
6    компьютер msi creator p50 11si-232xru
7      компьютер msi infinite 11si-1611xru
8      компьютер msi infinite 11th-1610xru
9            компьютер acer aspire tc-1660
Name: Название, dtype: object

In [2733]:
df2[column][df2[column] != 0 ].head(10)

0       игровой компьютер thunderobot alpha d i5-12400
1    игровой компьютер thunderobot bw iii pro xl d ...
2    игровой компьютер asus rog g15 tower dt g15dk-...
3                          компьютер must mbm114003070
4                       компьютер iru 310h5ge i3 10105
5                 игровой компьютер must mbm3600110722
6    игровой компьютер acer predator orion 3000 po3...
7       компьютер acer nitro 50 n50-640 (dg.e2ver.003)
8    игровой компьютер acer aspire tc-1660 dg.bgzer...
9        игровой компьютер acer tc-1660 (dg.bgzer.010)
Name: Название, dtype: object

In [2734]:
column = 'Объем SSD'

In [2735]:
def func(s):
    try:
        if s == 0:
            return 0.0
        if " ГБ" in s:
            return float(s.split(" ГБ")[0])
        elif " ТБ" in s:
            return float(s.split(" ТБ "))
        else:
            return s
    except Exception:
        pass
df1[column] = df1[column].apply(func)
df2[column] = df2[column].apply(func)

In [2736]:
print(df1[column][df1[column] != 0 ].unique())
print(df2[column][df2[column] != 0 ].unique())

[1024.  240.  512.  256.  500.  250.  480. 1000.  128.  120.]
[ 512.   nan  256.  500.  480.  960. 1512. 1480. 2512.  240. 1500. 1256.
  128.]


In [2737]:
column = 'Мышь'


In [2738]:
def func(s):
    try:
        if "в комплекте" in s:
            return 1
        else:
            return s
    except Exception:
        pass

df1[column] = df1[column].apply(func)


In [2739]:
print(df1[column].unique())
print(df2[column].unique())

[nan  1.]
[0. 1.]


In [2740]:
column = 'Клавиатура'

In [2741]:
def func(s):
    try:
        if "в комплекте" in s:
            return 1
        else:
            return s
    except Exception:
        pass

df1[column] = df1[column].apply(func)

In [2742]:
print(df1[column][df1[column] != 0 ].unique())
print(df2[column][df2[column] != 0 ].unique())

[nan  1.]
[1.]


In [2743]:
column = 'Процессор'

df1[column] = df1[column].str.lower()
df2[column] = df2[column].str.lower()

In [2744]:
def func(s):
    try:
        if "amd " in s:
            return s.replace("amd ryzen ", "")
        elif "intel " in s:
            return s.replace("intel ", "")[5:-1].replace(" ", "-")
        elif "core" in s:
            return s.replace("core ", "")
        elif "ryzen" in s:
            return s.replace("ryzen ", "")
        else:
            return s
    except Exception:
        pass

df1[column] = df1[column].apply(func)
df2[column] = df2[column].apply(func)

In [2745]:

combined_column = pd.concat([df1[column], df2[column]])


label_encoder.fit(combined_column.astype(str))


df1[column] = label_encoder.transform(df1[column].astype(str))
df2[column] = label_encoder.transform(df2[column].astype(str))

In [2746]:
print(df1[column][df1[column] != 0 ].unique())
print(df2[column][df2[column] != 0 ].unique())

[ 50  34  25  56  49 104   4  97  19  45  69  29   9  73  98  55  72  27
  37  12   8  80  22  31  20  42 100  16  62  40  44  59  61  53  58  79
 105  11 106  86  84  78  54  85  71  47  43  41  70  35  90 107  48   3
  99  67   5  82  89   7  18  10   2   6 103  87  39]
[ 56  12  51  37  15  57   8  33   1  26  45  11  50  46  38   7  74  76
  10  36  35  83  25  81  32  88  95  65  20  80  19  86  63  91  64  93
  30  66  92  17  87  94  28  52  68  14 101 102  75  22  77  23  60  13
  21  96  24]


In [2747]:
print(len(df1[column][df1[column] != 0 ].unique()))
print(len(df2[column][df2[column] != 0 ].unique()))

67
57


In [2748]:
column = set(df1.columns) & set(df2.columns)

df_full = df1.loc[:, column]

df_full.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 428 entries, 0 to 427
Data columns (total 20 columns):
 #   Column                    Non-Null Count  Dtype  
---  ------                    --------------  -----  
 0   Процессор                 428 non-null    int32  
 1   Гарантия                  428 non-null    float64
 2   Объем SSD                 428 non-null    float64
 3   Кард-ридер                428 non-null    object 
 4   Мышь                      56 non-null     float64
 5   Цена                      428 non-null    float64
 6   Количество ядер           428 non-null    float64
 7   Стандарт Wi-Fi            428 non-null    object 
 8   Количество отзывов        428 non-null    float64
 9   Название                  428 non-null    object 
 10  Операционная система      428 non-null    int32  
 11  Клавиатура                54 non-null     float64
 12  link                      428 non-null    object 
 13  Рейтинг                   428 non-null    float64
 14  Блок питан

C:\Users\ilya\AppData\Local\Temp\ipykernel_11888\3155891446.py:3: FutureWarning: Passing a set as an indexer is deprecated and will raise in a future version. Use a list instead.
  df_full = df1.loc[:, column]


In [2749]:
column = set(df1.columns) & set(df2.columns)

df_full = df1.loc[:, column]

df_full.drop(columns = ['Кард-ридер', 'Стандарт Wi-Fi','link', 'Тип вилки'], inplace = True)

df_full.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 428 entries, 0 to 427
Data columns (total 16 columns):
 #   Column                    Non-Null Count  Dtype  
---  ------                    --------------  -----  
 0   Процессор                 428 non-null    int32  
 1   Гарантия                  428 non-null    float64
 2   Объем SSD                 428 non-null    float64
 3   Мышь                      56 non-null     float64
 4   Цена                      428 non-null    float64
 5   Количество ядер           428 non-null    float64
 6   Количество отзывов        428 non-null    float64
 7   Название                  428 non-null    object 
 8   Операционная система      428 non-null    int32  
 9   Клавиатура                54 non-null     float64
 10  Рейтинг                   428 non-null    float64
 11  Блок питания              369 non-null    float64
 12  Разъем для наушников      428 non-null    float64
 13  Графика                   428 non-null    int32  
 14  Объем опер

C:\Users\ilya\AppData\Local\Temp\ipykernel_11888\1233808231.py:3: FutureWarning: Passing a set as an indexer is deprecated and will raise in a future version. Use a list instead.
  df_full = df1.loc[:, column]


In [2750]:
df1['Количество отзывов'] = pd.DataFrame({'Количество отзывов': np.random.normal(loc=10, scale=5, size=100)}).round(0)
df2['Количество отзывов'] = pd.DataFrame({'Количество отзывов': np.random.normal(loc=10, scale=5, size=100)}).round(0)

df1['Количество отзывов'] = df1['Количество отзывов'].clip(1, 30)
df1['Количество отзывов'] = df1['Количество отзывов'].clip(1, 30)

In [2751]:
df1 = df1.fillna(0)
df2 = df2.fillna(0)

In [2752]:
column = df_full.columns

df1 = df1.loc[:, column]
df2 = df2.loc[:, column]

df1.to_csv(f'data_citilink.csv', index=False)
df2.to_csv(f'data_eldorado.csv', index=False)